### ISSUE TITLE
Installation fails on YNH 2.5

### ISSUE THREAD

**Issue by NicolasPetton** [YunoHost-Apps/jenkins_ynh#8]
Hi! 

Trying to install Jenkins, I get the following error:

```
[...]
+ for i in '`seq 1 $timeout`'
+ test -e /var/lib/jenkins/updates/default.json
+ break
+ java -jar /var/lib/jenkins/jenkins-cli.jar -s http://petton.fr/jenkins install-plugin reverse-proxy-auth-plugin
Attention : ....................................................................................................................java.io.IOException: Premature EOF
Attention : 	at sun.net.www.http.ChunkedInputStream.readAheadBlocking(ChunkedInputStream.java:565)
Attention : 	at sun.net.www.http.ChunkedInputStream.readAhead(ChunkedInputStream.java:609)
Attention : 	at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:696)
+ ynh_exit_properly
Attention : 	at java.io.FilterInputStream.read(FilterInputStream.java:133)
+ exit_code=255
Attention : 	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3126)
+ '[' 255 -eq 0 ']'
Attention : 	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3120)
Attention : 	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3108)
Attention : 	at hudson.cli.CLI$1ClientSideImpl.<init>(CLI.java:628)
+ trap '' EXIT
+ set +eu
Attention : 	at hudson.cli.CLI.plainHttpConnection(CLI.java:654)
+ echo -e '!!\n  jenkins'\''s script has encountered an error. Its execution was cancelled.\n!!'
Attention : 	at hudson.cli.CLI._main(CLI.java:582)
+ type -t ynh_clean_setup
Attention : 	at hudson.cli.CLI.main(CLI.java:399)
Attention : !!
Attention :   jenkins's script has encountered an error. Its execution was cancelled.
```

**Comment by maniackcrudelis** [comment]
Hi,

Thank to report this issue, I've not seen this before.
This is not a problem with ynh 2.5, but with the last jenkins version.

In any case, it's should be fixed by this commit https://github.com/YunoHost-Apps/jenkins_ynh/commit/4f31b7624a7b948e6334c97d07e3dff58f3b9fac
